apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: {{.Values.replicasCount}}
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: {{.Values.mongo.deployment.container.name}}
          image: {{.Values.mongo.deployment.container.image}}
          ports:
            - containerPort: {{.Values.mongo.deployment.container.ports.containerPort}}
          volumeMounts:
            - name: {{.Values.mongo.deployment.container.volumeMounts.name}}
              mountPath: {{.Values.mongo.deployment.container.volumeMounts.mountPath}}
      volumes:
        - name: {{.Values.mongo.deployment.container.volumeMounts.name}}
          persistentVolumeClaim:
            claimName: {{.Values.mongo.pvc.name}}
