apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{.Values.service.selector.app}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
      nodePort: {{.Values.service.nodePort}}
  type: {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}
spec:
  replicas: {{.Values.replicasCount}}
  selector:
    matchLabels:
      app: {{.Values.deployment.selector.app}}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.selector.app }}
    spec:
      containers:
        - name: {{.Values.deployment.container.name}}
          image: {{.Values.deployment.container.image}}
          ports:
            - containerPort: {{.Values.deployment.container.ports.containerPort}}
          env:
          {{- range .Values.env.data }}
            - name: {{.key}}
              value: {{.value}}
          {{- end }}
          imagePullPolicy: Always